import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Inter, Jersey_20 } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jersey = Jersey_20({
  variable: "--font-jersey",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jersey.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
